AWSTemplateFormatVersion: '2010-09-09'
Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
  using Amazon API Gateway.
Parameters:
  TableNameParameter:
    Type: String
Resources:
  microservicehttpendpoint:
    Properties:
      CodeUri: s3://aws-sar-publishing/457062289be0f37b1b0a9e0ff684018f
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      Events:
        Api1:
          Properties:
            Method: ANY
            Path: /MyResource
          Type: Api
      Handler: index.handler
      MemorySize: 512
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableNameParameter
      Runtime: nodejs6.10
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
